### PR TITLE
Build assets

### PR DESCRIPTION
**Pull request by anthonydillon**
Committing the build files

### CODE REVIEW

**Review by b-m-f — APPROVED** [review]

**Comment by nottrobin** [comment]
Is there really no way around including the built assets in the repo?

Couldn't we just define a build step in package.json and document in the readme that the build step should be run before publishing?

**Review by nottrobin — CHANGES_REQUESTED** [review]
Is there really no way around including the built assets in the repo?

Couldn't we just define a build step in package.json and document in the readme that the build step should be run before publishing?

**Comment by anthonydillon** [comment]
This project has always included the build assets. The only way would be to require the websites to have a build step that builds requires the source. As our sites don't all have js building we build here and simply copy the build assets into the project.

I understand this is not ideal and I think introducing webpack to the sites would help when transpiling and bundling the js dependencies. But, until we have this set up this is how we use the cookie policy.

**Comment by nottrobin** [comment]
@anthonydillon 

> This project has always included the build assets.

I know it's had these built assets up to now - I'm suggesting we use this opportunity to change that.

> The only way would be to require the websites to have a build step that builds requires the source.

That is not the only way. The other way is to simply make sure there's a [prepublishOnly](https://docs.npmjs.com/misc/scripts) script defined, which runs the build steps, so that whenever the module is published the build happens and the built assets are published, but that they're not actually included in the repository. This is what I'm suggesting.

**Comment by nottrobin** [comment]
I filed a PR to illustrate my point:

https://github.com/canonical-webteam/cookie-policy/pull/21

If you think that's fine, just merge my PR.

**Pull request closed without merging**
