### PR TITLE
Add translation to Chinese based on document lang

### LINKED ISSUE #98: [COPY UPDATE] Chinese translation
Please update Cookie policy - cn from the [copy doc](https://docs.google.com/document/d/1WrpaKvSLbpN5ejgA5FRMLl9rzn9Gaq4AIGPCnSu3eHo/edit?usp=drivesdk)

Could we create a Chinese language version of the policy (also Japanese)?

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Added translation feature
- Added all the zh translations
- Added a zh demo for local testing
- Updated the README to recommend running a simple server

## QA
- Run `npm install`
- Run `npm run build`
- Run `python -m SimpleHTTPServer`
- Visit http://localhost:8000
- Check everything works as before
- Click the link to the Chinese version
- Check everything works and matches [the copy doc](https://docs.google.com/document/d/1WrpaKvSLbpN5ejgA5FRMLl9rzn9Gaq4AIGPCnSu3eHo/edit#)

Fixes https://github.com/canonical-web-and-design/cookie-policy/issues/98

### CODE REVIEW

**Comment by pmahnke** [comment]
could this see what language the user excepts and show the langage based on that?  like we do for takeovers?

**Comment by anthonydillon** [comment]
Do you mean base the language from the browser preferred language setting?

**Comment by pmahnke** [comment]
@anthonydillon yes, like we do for the homepage takeovers on ubuntu.com

```javascript
  function getPrimaryParentLanguage() {
    /**
    * Get the primary parent language
    *
    * Get the user's default language, and if it's a sub-language,
    * infer the parent language - e.g. for "en-GB", infer "en"
    */
    var language = navigator.language || navigator.userLanguage || navigator.browserLanguage || navigator.systemLanguage;

    if (language.indexOf('-') !== -1 ) {
      language = language.split('-')[0];
    }

    return language
  };

  // get the users language and remove any extra detail suffix (e.g. -gb)
  var primaryParentLanguage = getPrimaryParentLanguage();
```

you could keep the langage selector if you wanted, but users would get chinese/japanese first

**Comment by anthonydillon** [comment]
I decided to go target the `lang` attr as it is [the recommended way to declare the language](https://www.w3.org/International/questions/qa-html-language-declarations) on a website. Which is different for the homepage takeovers as the lang is the dynamic attribute. In this case it's not. What you reckon?

**Review by pmahnke — APPROVED** [review]
+1, I didn't see you were looking at the page itself, but that's great

**Pull request merged**
