### PR TITLE
Rebuilds CSS with newest Vanilla to remove leaking CSS styles

### LINKED ISSUE #12: Unnecessary grid CSS in built file
There is quite a lot of unnecessary grid related CSS in built file (like: `[grid-demo] [class*="col-"]{background:#cdcdcd;margin-bottom:1rem} ...`) leaking from Vanilla.

It was already fixed in Vanilla itself, so quite likely rebuilding with newer version should fix that.

### PR DESCRIPTION
**Pull request by bartaz**
Fixes #12

### CODE REVIEW

**Review by anthonydillon — CHANGES_REQUESTED** [review]
It looks like this branch just updates the build CSS. This will get overridden in the next branch. Do you need to update the vanilla dep in the package.json?

**Comment by bartaz** [comment]
`package.json` defines vanilla-framework as `"vanilla-framework": "^1.2.3"` which updates to latest `1.X.X` when installing.

But yes, to be safe it would be good to update package.json as well.

**Comment by bartaz** [comment]
@anthonydillon Updated Vanilla in package.json and added to yarn.lock

**Review by anthonydillon — APPROVED** [review]
Thanks :+1:

**Pull request merged**
